use cloud102;

DROP TABLE IF EXISTS MC_COMMENTS;

CREATE TABLE MC_COMMENTS
(
    CM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CM_FNAME VARCHAR(30) NOT NULL,
    CM_LNAME VARCHAR(30) NOT NULL,
    CM_TYPE VARCHAR(30),
    CM_COMMENT VARCHAR(80)
);

INSERT INTO MC_COMMENTS(CM_ID, CM_FNAME, CM_LNAME, CM_TYPE, CM_COMMENT)
VALUES (DEFAULT, 'Jane', 'Doe', 'General Comment', 'Hence the name changed but so did the comment.');

INSERT INTO MC_COMMENTS(CM_ID, CM_FNAME, CM_LNAME, CM_TYPE, CM_COMMENT)
VALUES (DEFAULT, 'John', 'Doe', 'General Comment', 'Test');




